"""guardrails 테이블

Revision ID: 6306b9eb46b5
Revises: f0eb7b45b540
Create Date: 2026-08-13 10:42:48.610085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6306b9eb46b5'
down_revision: Union[str, Sequence[str], None] = 'f0eb7b45b540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrails',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardrails')),
    sa.UniqueConstraint('name', 'version', name='uq_guardrails_name_version'),
    sa.UniqueConstraint('name', 'version_number', name='uq_guardrails_name_version_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guardrails')
    # ### end Alembic commands ###
