"""api_keys.scopes

Revision ID: f0eb7b45b540
Revises: 59cd189a7f5a
Create Date: 2026-08-13 10:26:58.742682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0eb7b45b540'
down_revision: Union[str, Sequence[str], None] = '59cd189a7f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='["proxy"]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'scopes')
    # ### end Alembic commands ###
